# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./src/WindowsAssist.h \
    ./src/ui/ShortcutWidget.h \
    ./qxtglobalshortcut5/core/qxtglobal.h \
    ./qxtglobalshortcut5/gui/qxtglobalshortcut.h
SOURCES += ./src/main.cpp \
    ./src/WindowsAssist.cpp \
    ./src/ui/ShortcutWidget.cpp \
    ./qxtglobalshortcut5/core/qxtglobal.cpp \
    ./qxtglobalshortcut5/gui/qxtglobalshortcut.cpp
FORMS += ./src/WindowsAssist.ui \
    ./src/ui/ShortcutWidget.ui
RESOURCES += WindowsAssist.qrc
